### ISSUE TITLE
Determine how to use artifacts published on Bintray

### ISSUE THREAD

**Issue by hectcastro** [azavea/docker-spark-jobserver#5]
Use artifacts published on [Bintray](https://bintray.com/spark-jobserver) vs. building Spark Job Server from source.

**Comment by lossyrob** [comment]
I'm imagining an SBT project that pulls the target JAR from an environment variable, and creates a fat jar via the `assembly` plugin. So when you'd need to do a similar thing you'd just set the appropriate env var, clone this sbt repo, do a "./sbt assembly" and that would create the jar. It wouldn't compile anything but would still need a "build" step that would assembly all the dependencies.
